title: DigiMic
tagline: The Digital Microbiome Platform
url: https://digimic.org
baseurl: ""
lang: en-GB
timezone: Europe/London
repository: DigiMicOrg/DigiMicOrg.github.io

author:
  name: DigiMicOrg

description: >-
  Open tools, workflows, and training materials for mechanistic digital
  microbiome research.

header_pages:
  - about.md
  - resources.md
  - team.md

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: https://github.com/DigiMicOrg
      title: DigiMicOrg on GitHub
