---
title: a try @ kroki.io graphs
edit_date_01 : 2021-12-20
---
In this post, I will try to incorporate https://kroki.io/[kroki.io] into this website. +
edit: in summary, I couldn't :)

Although that's not a lot like me is it?!? Naaah... unfortunately my obstinate stubborn nature doesn't allow me to give-up until I've exhausted every possibility of succeeding. So although not _ideal_ –if you want to keep your site purely in `.md` format– this method of using kroki in your website is very easy to implement with the help of https://github.com/Mogztter/asciidoctor-kroki[asciidoctor-kroki], and the pre-requisite https://github.com/asciidoctor/jekyll-asciidoc[jekyll-asciidoc] plugins. At the same time this setup gains you the ability to blog and write in `.adoc` format, which I consider to be a plus (you can read all about the advantages and comparisons against markdown https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#graduating-to-asciidoc[here]).

Without further a due, let's delve into few examples using the krokio.io syntax within a `.adoc` file.

Down below, you can see the code block and the generated diagram beneath it in pairs.

----
[graphviz]
....
digraph foo {
  graph [bgcolor=transparent]
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
....
----

[graphviz]
....
digraph foo {
  graph [bgcolor=transparent]
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
....

a block.diag example
[blockdiag]
....
blockdiag {
  Kroki -> generates -> "Block diagrams";

  Kroki [color = "greenyellow"];
  "Block diagrams" [color = "pink"];
}
....

an svgbob example.

[svgbob]
....
       ___     ___      .---+---+---+---+---.     .---+---+---+---.  .---.   .---.
   ___/   \___/   \     |   |   |   |   |   |    / \ / \ / \ / \ /   |   +---+   |
  /   \___/   \___/     +---+---+---+---+---+   +---+---+---+---+    +---+   +---+
  \___/   \___/   \     |   |   |   |   |   |    \ / \ / \ / \ / \   |   +---+   |
  /   \___/   \___/     +---+---+---+---+---+     +---+---+---+---+  +---+   +---+
  \___/   \___/   \     |   |   |   |   |   |    / \ / \ / \ / \ /   |   +---+   |
      \___/   \___/     '---+---+---+---+---'   '---+---+---+---'    '---'   '---'
....

a vegalite example;
[vegalite]
....
include::../_includes/charts/discretizingScales.vl.json[]
....

a nomnoml example;
[nomnoml]
....
[Pirate|eyeCount: Int|raid();pillage()|
  [beard]--[parrot]
  [beard]-:>[foul mouth]
]

[<table>mischief | bawl | sing || yell | drink]

[<abstract>Marauder]<:--[Pirate]
[Pirate]- 0..7[mischief]
[jollyness]->[Pirate]
[jollyness]->[rum]
[jollyness]->[singing]
[Pirate]-> *[rum|tastiness: Int|swig()]
[Pirate]->[singing]
[singing]<->[rum]

[<start>st]->[<state>plunder]
[plunder]->[<choice>more loot]
[more loot]->[st]
[more loot] no ->[<end>e]

[<actor>Sailor] - [<usecase>shiver me;timbers]
....